import { GarageItem } from '../types/garage';

export const MockGarage: GarageItem[] = [
  {
    engine: 997,
    hash: '-1045541610',
    fuel: 98,
    vehicle: 'Comet',
    body: 998,
    plate: '5DR943LZ',
    garage: 'Pillbox Garage Parking',
    brand: 'Pfister',
    type: 'car',
    state: "out",
  },
  {
    engine: 1000,
    hash: '-114291515',
    fuel: 99,
    vehicle: 'Bati 801',
    body: 998,
    plate: '2SH495CR',
    garage: 'Pillbox Garage Parking',
    brand: 'Pegassi',
    type: 'car',
    state: "garaged",
  },
  {
    engine: 1000,
    hash: '-825837129',
    fuel: 98,
    vehicle: 'Vigero',
    body: 1000,
    plate: '5XD271SC',
    garage: 'Caears 24 Parking',
    brand: 'Declasse',
    type: 'car',
    state: "garaged",
  },
  {
    engine: 976,
    hash: '-1030275036',
    fuel: 99,
    vehicle: 'Seashark',
    body: 994,
    plate: '6OK858YC',
    garage: 'LSYMC Boathouse',
    brand: 'Speedophile',
    type: 'boat',
    state: "garaged",
  },
  {
    engine: 1000,
    hash: '-1845487887',
    fuel: 100,
    vehicle: 'Volatus',
    body: 1000,
    plate: '9CF705ST',
    garage: 'Pillbox Garage Parking',
    brand: 'Buckingham',
    type: 'aircraft',
    state: "out",
  },
];